image: node0.10

cache:
  - /tmp/npm

script:
  - sudo chown ubuntu:ubuntu /tmp/npm
  - npm set cache /tmp/npm
  - npm config set registry http://npm.iteam.se:4873/
  - npm -s install --production
  - ./node_modules/.bin/bower install
  - ./node_modules/.bin/grunt deploy:$DRONE_BRANCH

notify:

  slack:
    team: iteamsolutions
    channel: #marknad
    username: drone.io
    token: 8CucDNnAVELD0BBEErMnhobE
    on_started: false
    on_failure: true
    on_success: false

