image: node0.10

script:
  - npm -s install
  - npm -s install -g grunt-cli docpad bower
  - bower install
  - grunt deploy:$DRONE_BRANCH

notify:

  slack:
    team: iteamsolutions
    channel: #marknad
    username: drone.io
    token: 8CucDNnAVELD0BBEErMnhobE
    on_started: false
    on_failure: true
    on_success: false

