image: node0.10
cache:
  - /tmp/npm

script:
  - mkdir -p /tmp/npm
  - sudo chown -R ubuntu:ubuntu /tmp/npm
  - cp -rf /tmp/npm .
  - npm -s install
  - npm -s install -g grunt-cli docpad bower
  - bower install
  - grunt deploy:$DRONE_BRANCH
  - cp -rf node_modules /tmp/npm

notify:

  slack:
    team: iteamsolutions
    channel: #marknad
    username: drone.io
    token: 8CucDNnAVELD0BBEErMnhobE
    on_started: false
    on_failure: true
    on_success: false

